version: '3.9'
services:
    frontend:
        container_name: viewer
        build: .
        ports:
            - '3000:80'
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        #restart: always
