// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly VITE_ENV_NAME: string
  readonly VITE_BASE_URL: string
  readonly VITE_APP_TITLE: string
  readonly VITE_COPYRIGHT: string
  readonly VITE_PORT: string
  readonly VITE_HOST_API: string
  readonly VITE_HOST_MEDIASERVICE: string
  readonly VITE_BASE_URL_MEDIASERVICE: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
